name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Keep scheduled workflow activity
        uses: WaterLemons2k/scheduled-workflow-activity-action@v1

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Set up NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: "r25b"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Get version from gradle file
        id: get_version
        run: |
          VERSION_NAME=$(grep "versionName \"" app/build.gradle | sed 's/.*"\(.*\)".*/\1/')
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_OUTPUT

      - name: Decode Keystore
        run: echo "${{ secrets.SIGNING_KEY_STORE_BASE64 }}" | base64 --decode > app/my-release-key.keystore

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APKs
        run: ./gradlew assembleRelease assembleDebug
        env:
          SIGNING_KEY_STORE_PASSWORD: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Find APK files
        id: find_apks
        run: |
          RELEASE_APK=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          DEBUG_APK=$(find app/build/outputs/apk/debug -name "*.apk" | head -n 1)
          echo "RELEASE_APK_PATH=${RELEASE_APK}" >> $GITHUB_OUTPUT
          echo "DEBUG_APK_PATH=${DEBUG_APK}" >> $GITHUB_OUTPUT

      - name: Delete old releases
        uses: Nats-ji/delete-old-releases@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-count: 0
          keep-old-minor-releases: false
          remove-tags: true

      - name: Release and upload assets
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION_NAME }}
          name: Release v${{ steps.get_version.outputs.VERSION_NAME }}
          files: |
            ${{ steps.find_apks.outputs.RELEASE_APK_PATH }}
            ${{ steps.find_apks.outputs.DEBUG_APK_PATH }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
